version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379' 
    networks:
      - webnet

  express-server:
    image: express:latest
    ports:
      - '3000:3000'  
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - webnet
    depends_on:
      - redis
    restart: always


networks:
  webnet:
    driver: bridge